<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEECmI7S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEECmI7S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEECmI7S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEECmI7S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEECmI7S\App_KernelDevDebugContainer([
    'container.build_hash' => 'EECmI7S',
    'container.build_id' => '9388858c',
    'container.build_time' => 1704283429,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEECmI7S');
